---
title: "Teaching"
---
<p>&nbsp;</p>
<font size="3"><b><i>Course Instruction, University of Alaska system</b></i></font>
<p>Instructor (co-taught with T. Hollmen), University of Alaska Fairbanks (Jan-May 2023)
<br>Marine Bird Ecology and Conservation (MSL F410, 3 credits) - Undergraduate course in the College of Fisheries and Ocean Sciences

<p>Instructor, University of Alaska Fairbanks (Sept – Oct 2022)
<br>Fact of Fishin': Case studies in fisheries and marine science (FISH/MSL F102, 1 credit) - Undergraduate seminar in the College of Fisheries and Ocean Sciences

<p>Instructor, University of Alaska Fairbanks (Jan – May 2022)
<br>Fisheries and Ocean Sciences Weekly Seminar (MSL 492/692, 1 credit) - Undergraduate/graduate course in the College of Fisheries and Ocean Sciences

<p>Instructor, University of Alaska Fairbanks (Jan – May 2020)
<br>Marine Biology (MSL F610, 3 credits) – Graduate course in the College of Fisheries and Ocean Sciences

<p>Adjunct Instructor, University of Alaska Fairbanks (Jan – May 2019)
<br>Principles of Evolution (BIOL481/681, 4 credits) – Undergraduate course in the Biology & Wildlife Department

<p>Adjunct Instructor, University of Alaska Southeast (Jan – May 2017)
<br>Evolution (BIOL S482, 4 credits) - Undergraduate capstone course in the Biology and Marine Biology Department
<p>&nbsp;</p>
<HR>
<font size="3"><b><i>Student Mentorship, University of Alaska Fairbanks</b></i></font>

**Graduate Student Committees**
<br>Brett Carouthers, MS graduate student (UAF, Marine Biology). Major Professor: Dr. Lara Horstmann
<br>Katie Stoner, PhD graduate student (Oregon State U, Fish and Wildlife). Major Professor: Dr. Don Lyons
<br>Lindsey Stadler. MS graduate student (UAF, Marine Biology). Major Professor: Dr. Katrin Iken
<br>Elizabeth Hasan. MS graduate student (UAF, Marine Biology). Major Professor: Dr. Brenda Konar
<br>Brian Ulaski. PhD candidate (UAF, Marine Biology). Major Professor: Dr. Brenda Konar
<br>Chris Guo. PhD graduate student (UAF, Marine Biology). Major Professor: Dr. Brenda Konar
<br>Drew Porter. MS graduate student (UAF, Marine Biology, graduated 2022). Major Professor: Dr. Mat Wooller
<br>Julia McMahon. MS graduate student (UAF, Fisheries, graduated 2021). Major Professor: Dr. Peter Westley

**Undergraduate Students**
<br>Nana Matsui. BS undergraduate student (UAF, Fisheries and Ocean Sciences, graduated 2021). Advisor: Dr. Lara Horstmann
<p>&nbsp;</p>
<HR>
<font size="3"><b><i>Service, University of Alaska Fairbanks and beyond</b></i></font>

Proposal reviewer for Arctic-Yukon-Kuskokwim Sustainable Salmon Initiative (September 2022).

Review editor for Frontiers in Marine Science, Marine Megafauna section (August 2022–Present).

Institutional Animal Care and Use Committee (IACUC) member, University of Alaska Fairbanks, Fairbanks, Alaska (July 2021 - present)

Peer-review of manuscripts for Antarctic Science (1), Biology Letters (4), Canadian Journal of Fisheries and Aquatic Sciences (1), Deep-Sea Research II (1), Global Change Biology (1), Journal of Animal Ecology (1), Journal of Avian Biology (1), Marine Ecology Progress Series (5), Marine Ornithology (1), Physiological and Biochemical Zoology (4), Polar Biology (4), The American Naturalist (1), USGS internal review (1), Waterbirds (1).

Peer-review (with honorarium) of Marine Biology: function, diversity, and ecology (6th edition, Oxford University Press) textbook by Jeffery Levinton.

Co-chair of the 2016 Alaska Bird Conference, Cordova, Alaska, December 2016.
<p>&nbsp;</p>
<HR>
Updated 2 Sept 2022